apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata-clh-snp
handler: kata-clh-snp
scheduling:
  nodeSelector:
    node.kubernetes.io/sev-snp: "true"
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata-clh-tdx
handler: kata-clh-tdx
scheduling:
  nodeSelector:
    feature.node.kubernetes.io/tdx: "true"
