apiVersion: aether/v1
kind: Workload
metadata:
  name: demo-kubevirt-metal3
  owner: demo
  project: aether-demos
build:
  context: "."
  dockerfile: Dockerfile
  registry: localhost
requirements:
  cpu: "8"
  memory: 32Gi
  storage: 100Gi
runtime:
  preferred: kubevirt
  allow:
    - kubevirt
    - metal3
network:
  service: true
  ports:
    - containerPort: 8080
      servicePort: 8080
intent:
  goal: high-throughput
