{{- $createSecret := or .Values.apiKey.value .Values.postgresql.databaseUrl .Values.redis.url .Values.oidc.enabled .Values.saml.enabled .Values.ldap.enabled .Values.backupRemote.enabled .Values.auditWebhook.enabled }}
{{- if $createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aether.fullname" . }}-secrets
  labels:
    {{- include "aether.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.apiKey.value }}
  api-key: {{ .Values.apiKey.value | quote }}
  {{- end }}
  {{- if .Values.postgresql.databaseUrl }}
  {{ .Values.postgresql.secretKey }}: {{ .Values.postgresql.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.redis.url }}
  {{ .Values.redis.secretKey }}: {{ .Values.redis.url | quote }}
  {{- end }}
  {{- if .Values.oidc.enabled }}
  issuer: {{ .Values.oidc.issuer | quote }}
  client-id: {{ .Values.oidc.clientId | quote }}
  redirect-uri: {{ .Values.oidc.redirectUri | quote }}
  session-secret: {{ .Values.oidc.sessionSecret | quote }}
  {{- if .Values.oidc.clientSecret }}
  client-secret: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oidc.roleMap }}
  oidc-role-map: {{ .Values.oidc.roleMap | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.saml.enabled }}
  saml-idp-sso-url: {{ .Values.saml.idpSsoUrl | quote }}
  saml-idp-entity-id: {{ .Values.saml.idpEntityId | quote }}
  saml-acs-url: {{ .Values.saml.acsUrl | quote }}
  saml-session-secret: {{ .Values.saml.sessionSecret | default .Values.oidc.sessionSecret | quote }}
  {{- if .Values.saml.spEntityId }}
  saml-sp-entity-id: {{ .Values.saml.spEntityId | quote }}
  {{- end }}
  {{- if .Values.saml.idpCert }}
  saml-idp-cert: {{ .Values.saml.idpCert | quote }}
  {{- end }}
  {{- if .Values.saml.roleMap }}
  saml-role-map: {{ .Values.saml.roleMap | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.ldap.enabled }}
  ldap-url: {{ .Values.ldap.url | quote }}
  ldap-base-dn: {{ .Values.ldap.baseDn | quote }}
  ldap-session-secret: {{ .Values.ldap.sessionSecret | default .Values.oidc.sessionSecret | quote }}
  {{- if .Values.ldap.domain }}
  ldap-domain: {{ .Values.ldap.domain | quote }}
  {{- end }}
  {{- if .Values.ldap.bindDn }}
  ldap-bind-dn: {{ .Values.ldap.bindDn | quote }}
  {{- end }}
  {{- if .Values.ldap.bindPassword }}
  ldap-bind-password: {{ .Values.ldap.bindPassword | quote }}
  {{- end }}
  {{- if .Values.ldap.roleMap }}
  ldap-role-map: {{ .Values.ldap.roleMap | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.backupRemote.enabled }}
  backup-remote-url: {{ .Values.backupRemote.url | quote }}
  {{- if .Values.backupRemote.token }}
  backup-remote-token: {{ .Values.backupRemote.token | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.auditWebhook.enabled }}
  audit-webhook-url: {{ .Values.auditWebhook.url | quote }}
  {{- end }}
{{- end }}
