/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        surface: 'var(--surface)',
        primary: 'var(--primary)',
        muted: 'var(--muted-foreground)',
        border: 'var(--border)',
        danger: 'var(--danger)',
        warn: 'var(--warning)',
        success: 'var(--success)',
        canvas: 'var(--canvas)',
        page: 'var(--page)',
        sunken: 'var(--sunken)',
        raised: 'var(--raised)',
        hover: 'var(--hover)',
        selected: 'var(--selected)',
        rule: 'var(--rule)',
        'rule-strong': 'var(--rule-strong)',
        ink: 'var(--ink)',
        'ink-2': 'var(--ink-2)',
        'ink-3': 'var(--ink-3)',
        brand: 'rgb(var(--brand-rgb) / <alpha-value>)',
        'brand-ink': 'var(--brand-ink)',
        'brand-wash': 'var(--brand-wash)',
        scrim: 'var(--scrim)',
        glass: 'var(--glass)',
        deepblue: 'rgb(var(--iphone-deep-blue-rgb) / <alpha-value>)',
        sage: 'rgb(var(--iphone-sage-rgb) / <alpha-value>)',
        mistblue: 'rgb(var(--iphone-mist-blue-rgb) / <alpha-value>)',
        lavender: 'rgb(var(--iphone-lavender-rgb) / <alpha-value>)',
        gold: 'rgb(var(--iphone-gold-rgb) / <alpha-value>)',
        aether: {
          DEFAULT: '#0071e3',
          light: '#0a84ff',
          dark: '#0058b3',
          dim: 'rgba(0, 113, 227, 0.14)',
          glow: 'rgba(0, 113, 227, 0.28)',
        },
        'aether-ai': {
          DEFAULT: '#0071e3',
          light: '#409cff',
          dark: '#0058b3',
          dim: 'rgba(0, 113, 227, 0.14)',
          glow: 'rgba(0, 113, 227, 0.28)',
        },
      },
      fontFamily: {
        sans: ['var(--sans)'],
        display: ['var(--font-display)'],
        mono: ['var(--mono)'],
      },
      boxShadow: {
        ambient: 'var(--shadow)',
        card: 'var(--shadow-card)',
      },
      borderRadius: {
        liquid: 'var(--radius-liquid)',
        pill: 'var(--radius-pill)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
};
